@baseurl = http://localhost:5001/gimmefood-d4740/us-central1/api

# @name helloWorld
GET {{baseurl}} HTTP/1.1
Content-Type: application/json

### 

# @name seedDb
POST {{baseurl}}/seed HTTP/1.1
Content-Type: application/json

###

# @name fetchPosts
GET {{baseurl}}/food HTTP/1.1
Content-Type: application/json

###
@cursor = {{fetchPosts.response.body.pageInfo.endCursor}}

# @name fetchPostsBasedCursor
GET {{baseurl}}/food?cursor={{cursor}} HTTP/1.1
Content-Type: application/json
