@baseurl = http://localhost:5001/gimmefood-d4740/us-central1

# @name posts
GET {{baseurl}}/posts HTTP/1.1
Content-Type: application/json

###
@cursor = {{posts.response.body.pageInfo.endCursor}}

# @name postsWithCursor
GET {{baseurl}}/posts?cursor={{cursor}} HTTP/1.1
Content-Type: application/json
