name: Firebase Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install dependencies
        run: cd functions/ && yarn install

      - name: create env file
        run: |
          cd functions/
          touch .env
          echo ${{ secrets.DOTENV_CONFIG }} >> .env
          
      - name: deploy to production
        uses: w9jds/firebase-action@v2
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
