name: Firebase Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: |
          cd functions/
          yarn install --immutable

      - name: create env file
        run: |
          cd functions/
          touch .env
          echo ${{ secrets.DOTENV_CONFIG }} >> .env

      - name: deploy to production
        run: |
          cd functions/
          yarn deploy --token "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GIMMEFOOD_D4n740 }}" --non-interactive --security-level=secure-always
