name: Build and test

"on":
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: functions/yarn.lock

      - name: install dependencies, lint & build
        run: |
          cd functions/
          yarn install --immutable
          yarn lint
          yarn build
