name: Deploy to firebase

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  deploy_to_firebase:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: functions/yarn.lock

      - name: install dependencies
        run: |
          npm i -g firebase-tools
          cd functions/
          yarn install --immutable

      - name: create .env file
        run: |
          cd functions/
          touch .env
          echo BLEND_ADMIN_KEY=${{ secrets.BLEND_ADMIN_KEY }} >> .env
          echo BLEND_CLIENT_EMAIL=${{ secrets.BLEND_CLIENT_EMAIL }} >> .env
          echo BLEND_PROJECT_ID=${{ secrets.BLEND_PROJECT_ID }} >> .env
          echo UNSPLASH_API_KEY=${{ secrets.UNSPLASH_API_KEY }} >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env

      - name: deploy to firebase
        run: |
          cd functions/
          yarn deploy --only functions --token ${{ secrets.DEPLOY_TOKEN }}
